import type { Metadata } from "next";
import { Quicksand, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar" 
import Header from "./components/header/Header"

const quickSand = Quicksand({
  variable: "--font-quicksand"
});

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${quickSand.variable} ${beVietnamPro.variable}`}>
      <body>
        <Header />
        {children}
        <Navbar />
      </body>
    </html>
  );
}
